import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from email.mime.application import MIMEApplication
import os

from config import logger, GMAIL_SENDER, GMAIL_APP_PASSWORD, GMAIL_RECIPIENTS, TIMEZONE
from utils import get_week_label

def send(pdf_path: str, data: dict):
    if not os.path.exists(pdf_path):
        logger.error(f"Cannot send email. PDF not found at {pdf_path}")
        return
        
    if not GMAIL_SENDER or not GMAIL_APP_PASSWORD or not GMAIL_RECIPIENTS:
        logger.error("Gmail credentials or recipients missing in .env. Skipping email.")
        return
        
    logger.info(f"Sending email to {len(GMAIL_RECIPIENTS)} recipients...")
    
    stats = data.get('stats', {})
    crit_count = stats.get('critical_count', 0)
    week_label = get_week_label(TIMEZONE)
    
    subject = f"🔐 Cyber Intelligence Weekly | {week_label} | {crit_count} Critical Alerts"
    
    msg = MIMEMultipart()
    msg['From'] = GMAIL_SENDER
    msg['To'] = ", ".join(GMAIL_RECIPIENTS)
    msg['Subject'] = subject
    
    # HTML Body
    html_body = f"""
    <html>
      <body style="font-family: Arial, sans-serif; line-height: 1.6; color: #333;">
        <h2>Cyber Intelligence Weekly Briefing</h2>
        <p><strong>{data.get('week_label', week_label)}</strong></p>
        
        <div style="background: #f8f9fa; padding: 15px; border-left: 4px solid #C8102E; margin-bottom: 20px;">
          <h3 style="margin-top: 0; font-size: 14px; text-transform: uppercase; color: #555;">Executive Summary</h3>
          <p>{data.get('executive_summary', 'See attached PDF for full details.')}</p>
        </div>
        
        <p><strong>Quick Stats:</strong></p>
        <ul>
          <li>Critical Alerts: {crit_count}</li>
          <li>High Alerts: {stats.get('high_count', 0)}</li>
          <li>CVEs Identified: {stats.get('cves_identified', 0)}</li>
        </ul>
        
        <p>Please find the full visual report attached as a PDF.</p>
        
        <br>
        <hr>
        <p style="font-size: 11px; color: #888;">
          Generated by Cyber Intelligence Automation.<br>
          <i>This report contains only information from verified public sources. No AI-generated claims.</i>
        </p>
      </body>
    </html>
    """
    
    msg.attach(MIMEText(html_body, 'html'))
    
    # Attach PDF
    with open(pdf_path, 'rb') as f:
        pdf_attachment = MIMEApplication(f.read(), _subtype="pdf")
        pdf_attachment.add_header('Content-Disposition', 'attachment', filename=os.path.basename(pdf_path))
        msg.attach(pdf_attachment)
        
    # Send
    try:
        server = smtplib.SMTP('smtp.gmail.com', 587)
        server.starttls()
        server.login(GMAIL_SENDER, GMAIL_APP_PASSWORD)
        server.send_message(msg)
        server.quit()
        logger.info("Newsletter email sent successfully via Gmail SMTP.")
    except smtplib.SMTPAuthenticationError:
        logger.error(
            "Gmail Authentication Failed! \n"
            "Action Required: \n"
            "1. You cannot use your normal Gmail password.\n"
            "2. Go to Google Account -> Security -> 2-Step Verification.\n"
            "3. Scroll to bottom -> App Passwords.\n"
            "4. Generate a new App Password.\n"
            "5. Place that 16-character password in your .env file."
        )
    except Exception as e:
        logger.error(f"Failed to send email: {e}")
